config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  scope ':username' do
    resources :posts do
      resources :likes, only: %i[create destroy]
      resources :comments, except: %i[index destroy]
    end
    resources :message, only: %i[index new create]
  end

  resources :feeds, only: %[index]
  root 'feeds#index'

  resources :friendships, except: [:destroy]
  delete '/friendships', to: 'friendships#destroy'
  post '/send_request', to: 'friendships#request_create'
  get '/message/friends', to: 'friendships#list_friends'

  resources :find_friends, only: %i[new index create]
  delete '/find_friends', to: 'find_friends#destroy'

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  devise_scope :user do
    get 'login', to: 'friendships#index'
  end
end

app/models/feed.rb
class Feed
  #there has to be a way to remove the current_user nuisance
  def self.posts(current_user)
    friends_posts(current_user).order('updated_at DESC') + non_friend_public_posts(current_user).order('updated_at DESC')
  end

  def self.friends_posts(current_user)
    Post.includes(:creator).where(user_id: friends_ids(current_user))
  end

  def self.non_friend_public_posts(current_user)
    Post.includes(:creator).where.not(user_id: friends_ids(current_user)+[current_user.id])
  end

  private

  def self.friends_ids(current_user)
    User.friends(current_user).pluck(:id)
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController

  before_action :authenticate_user!

  def index
    @posts = Feed.posts(current_user)
  end
  
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/index.html.erb
<div class='feeds'>
  <div class='header links'>
  <%= link_to "New post", new_post_path(current_user.username) %>
  <%= link_to "My posts", posts_path(current_user.username) %>
  <%= link_to "Friends", friendships_path %>
  <%= link_to "Find Friends", find_friends_path %>
  <%= link_to "Chat", message_friends_path %>
  <%= link_to 'Log Out', destroy_user_session_path %> 
  </div>


  <div id="posts">
    <% @posts.each do |post| %>
      <div class='card'>
        <% @post = post %>
        <%= render @post %>
        <% like = Like.metadata(post, current_user) %>
        <% unless like.exists? %>
        <%= render partial: "likes/like_button_form", locals: {post_id: post.id} %>
        <% else %>
        <%= render partial: "likes/dislike_button_form", locals: {post_id: post.id, like_id: like.first.id} %>
        <% end %>
        <p>
          <%= link_to "Show this post", post_url(post.creator.username,@post) %>
        </p>
      </div>
    <% end %>
  </div>
</div>