config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  scope ':username' do
    resources :posts do
      resources :likes, only: %i[create destroy]
      resources :comments, except: %i[index destroy]
    end
    resources :message, only: %i[index new create]
  end

  resources :feeds, only: %[index]
  root 'feeds#index'

  resources :friendships, except: [:destroy]
  delete '/friendships', to: 'friendships#destroy'
  post '/send_request', to: 'friendships#request_create'
  get '/message/friends', to: 'friendships#list_friends'

  resources :find_friends, only: %i[new index create]
  delete '/find_friends', to: 'find_friends#destroy'

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  devise_scope :user do
    get 'login', to: 'friendships#index'
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_closure_tree
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  belongs_to :original_post, foreign_key: 'post_id', class_name: 'Post'

  validates :body, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /comments or /comments.json
  def index
    @comments = Comment.hash_tree
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.creator = current_user
    @comment.post_id = params[:post_id]

    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_url(Post.find(params[:post_id]).creator.username, params[:post_id]), notice: "Comment was successfully made." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { redirect_to post_url(Post.find(params[:post_id]).creator.username, params[:post_id]), notice: "Something went wrong." }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:body, :parent_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
</div>

app/views/comments/_form.html.erb
  <%= form_with(model: @comment, url: post_comments_url(current_user.username, @post), scope: :comment) do |form| %>
    <div>
    <p>
      <%= form.text_area :body, cols:'80', rows:'5' %>
    </p>
     <%= form.hidden_field :parent_id, value: parent_id%>
    <p>
    <%= form.submit "#{button}"%>
    </p>
    </div>
  <% end %>

app/views/comments/_index.html.erb
<% comments.includes(:creator, :children).each do |comment| %>
  <p><b><%= comment.creator.username %></b><br>
  <%= comment.body %></p>
  <% comment_id = "comment_"+comment.id.to_s %>
  <%= content_tag :div, class:["reply-form", comment_id] do %>
    <%= render partial:'comments/form', locals: { button: 'Reply', parent_id: comment. id } %> 
  <% end -%>

  <%= content_tag :div, class:["reply-link", comment_id] do %>
    <%= link_to 'Reply' %>     
  <% end -%>
  <% unless comment.children.empty? %>
  <div class = 'nesting'>
  <%= render partial: 'comments/index', locals: { comments: comment.children, level: level+1}%>
  </div>
  <% end %>
<% end %>

<%= render partial:'comments/form', locals: { button: 'Comment', parent_id: nil } if level == 1 %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>