config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  scope ':username' do
    resources :posts do
      resources :likes, only: %i[create destroy]
      resources :comments, except: %i[index destroy]
    end
    resources :message, only: %i[index new create]
  end

  resources :feeds, only: %[index]
  root 'feeds#index'

  resources :friendships, except: [:destroy]
  delete '/friendships', to: 'friendships#destroy'
  post '/send_request', to: 'friendships#request_create'
  get '/message/friends', to: 'friendships#list_friends'

  resources :find_friends, only: %i[new index create]
  delete '/find_friends', to: 'find_friends#destroy'

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  devise_scope :user do
    get 'login', to: 'friendships#index'
  end
end

app/models/friendship.rb
# frozen_string_literal: true

class Friendship < ApplicationRecord
  belongs_to :metadata, class_name: 'FriendRequest'

  def self.connections(current_user)
    all_connections = FriendRequest.joins('INNER JOIN friendships ON friend_requests.id = friendships.metadata_id')\
                                   .where('sender_id=? OR receiver_id=?', current_user.id, current_user.id)
    all_connections.where('sender_id=?', current_user.id).or(all_connections.where('receiver_id=?', current_user.id))\
                   .includes(:sender, :receiver)
  end

  def self.requests(current_user)
    anti_join = FriendRequest.joins('LEFT JOIN friendships ON friend_requests.id = friendships.metadata_id')\
                             .where('friendships.metadata_id IS NULL')
    anti_join.where(receiver_id: current_user.id)
  end

  def self.friend(connection, current_user)
    return connection.receiver.username unless connection.receiver.id == current_user.id

    connection.sender.username
  end
end

app/controllers/friendships_controller.rb
# frozen_string_literal: true

class FriendshipsController < ApplicationController
  before_action :authenticate_user!

  # GET /friendships or /friendships.json
  def index
    @connections = Friendship.connections(current_user)
    @friend_requests = Friendship.requests(current_user)
  end

  # GET /friendships/new
  def new
    @friendship = Friendship.new
  end

  # POST /friendships or /friendships.json
  def create
    @friendrequest_id = friendship_params[:friendrequest_id]
    @friendship = Friendship.new(metadata_id: @friendrequest_id)
    @friendship = nil unless FriendRequest.find(@friendrequest_id).receiver == current_user

    respond_to do |format|
      if @friendship.save
        format.turbo_stream{ flash.now[:notice] = "Friend Request successfully accepted" }
        format.html { redirect_to friendships_url, notice: 'FriendRequest successfully accepted' }
      end
    end
  end

  def destroy
    @connection = FriendRequest.find(friendship_params[:friendrequest_id])
    destroyed = @connection.destroy if @connection.sender == current_user || @connection.receiver == current_user

    respond_to do |format|
      format.turbo_stream{ flash.now[:notice] = "Friend successfully unfriended" }
      format.html { redirect_to friendships_url, notice: 'Friendship was successfully destroyed.' }
    end
  end

  def list_friends
    @friends = User.friends(current_user)
  end

  private

  def friendship_params
    params.require(:friendship).permit(:friendrequest_id)
  end
end

app/helpers/friendships_helper.rb
# frozen_string_literal: true

module FriendshipsHelper
end

app/views/friendships/_accept_friendship_form.html.erb
<%= form_with(model: @friendship, scope: :friendship) do |form| %>
    <%= form.hidden_field :friendrequest_id, value: friendrequest_id %>
    <%= form.submit "Accept", data: { turbo_confirm: "Are you sure?" } %>
<% end %>

app/views/friendships/_friendship.html.erb
<div id="<%= dom_id friendship %>">
</div>

app/views/friendships/_remove_friend.html.erb
  <%= form_with(model: @friendship, scope: :friendship, method: :delete) do |form| %>
    <%= form.hidden_field :friendrequest_id, value: accepted_friendrequest.id %>
    <%= form.submit "Remove", data: { turbo_confirm: "Are you sure?" } %>
  <% end %>

app/views/friendships/_remove_friend_form.html.erb
<%= form_with(model: @friendship, scope: :friendship, method: :delete) do |form| %>
    <%= form.hidden_field :friendrequest_id, value: friendrequest_id %>
    <%= form.submit "Remove", data: { turbo_confirm: "Are you sure?" } %>
<% end %>

app/views/friendships/create.turbo_stream.erb
<%= turbo_stream.replace "flash", partial: "layouts/flash" %>
<%= turbo_stream.remove "friend_request_#{@friendrequest_id}" %>

app/views/friendships/destroy.turbo_stream.erb
<%= turbo_stream.replace "flash", partial: "layouts/flash" %>
<%= turbo_stream.remove dom_id(@connection, :successful) %>

app/views/friendships/edit.html.erb
<h1>Editing friendship</h1>

<%= render "form", friendship: @friendship %>

<br>

<div>
  <%= link_to "Show this friendship", @friendship %> |
  <%= link_to "Back to friendships", friendships_path %>
</div>

app/views/friendships/index.html.erb
<h4>Friends</h4>

<div id="friendships">
  <% @connections.includes(:sender, :receiver) %>
  <% @connections.each do |connection| %>
    <%= Friendship.friend(connection,current_user) %>
    <%= render partial: "remove_friend", locals: { accepted_friendrequest: connection } %>
    <br>
  <% end %>
</div>

<h4>Friend Requests</h4>
<div id="friend_requests">
  <% @friend_requests.includes(:sender) %>
  <% @friend_requests.each do |request| %>
  <%= turbo_frame_tag dom_id(request) do %> 
    <%= request.sender.username %><br>
    <%= render partial: "accept_friendship_form", locals: { friendrequest_id: request.id } %>
  <% end %>
  <% end %>
</div>

app/views/friendships/list_friends.html.erb
<div class='friendlist'>
<% @friends.each do |friend| %>
<div class='friend card'>
  <%= content_tag :div, class: "friend name" do %>
    <%= friend.username %>
  <% end %>
  <%= content_tag :div, class: ["friend", 'chat'] do %>
    <%= button_to 'Chat', message_index_path(friend.username), method: :get %>
  <% end %>
</div>
<% end %>

app/views/friendships/new.html.erb
<h1>New friendship</h1>

<%= render "form", friendship: @friendship %>

<br>

<div>
  <%= link_to "Back to friendships", friendships_path %>
</div>

app/views/friendships/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @friendship %>

<div>
  <%= link_to "Edit this friendship", edit_friendship_path(@friendship) %> |
  <%= link_to "Back to friendships", friendships_path %>

  <%= button_to "Destroy this friendship", @friendship, method: :delete %>
</div>