config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  scope ':username' do
    resources :posts do
      resources :likes, only: %i[create destroy]
      resources :comments, except: %i[index destroy]
    end
    resources :message, only: %i[index new create]
  end

  resources :feeds, only: %[index]
  root 'feeds#index'

  resources :friendships, except: [:destroy]
  delete '/friendships', to: 'friendships#destroy'
  post '/send_request', to: 'friendships#request_create'
  get '/message/friends', to: 'friendships#list_friends'

  resources :find_friends, only: %i[new index create]
  delete '/find_friends', to: 'find_friends#destroy'

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  devise_scope :user do
    get 'login', to: 'friendships#index'
  end
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
  validates :title, length: { minimum: 10 }
  validates :body, length: { minimum: 30 }

  has_many :likes
  has_many :users_who_liked, through: :likes, source: :user
  has_many :comments
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_username, except: %i[index show]
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /posts or /posts.json
  def index
    @posts = Post.includes(:creator).where('user_id = ?', user.id)
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post = Post.find_by(user_id: user.id, id: params[:id])
    @comments = Comment.where(post_id:@post.id).roots
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    @posts = Post.where('user_id = ?', user.id)
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.creator = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(current_user.username, @post), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(current_user.username, @post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    respond_to do |format|
      if @post.destroy
        format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  def set_username
    user
    return if @user.username == current_user.username

    redirect_to posts_url(current_user.username),
                notice: 'You cannot access that page'
  end

  def user
    @user = User.where('lower(username) = ?', params[:username].downcase).first
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/posts/_edit_links.html.erb
<div>
  <%= link_to "Edit this post", edit_post_path(current_user.username,post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", post_url(current_user.username,post), method: :delete %>
</div>

app/views/posts/_form.html.erb
<%= form_with model: post, url: url do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 <p>
  <%= form.label :title %><br>
  <%= form.text_field :title %>
 </p>

 <p>
  <%= form.label :body %><br>
  <%= form.text_area :body, rows: 10, cols: 27 %>
 </p>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
<h1><%= @post.title %></h1>

<p><%= @post.body %></p>

<p><i>by <%= @post.creator.username %></i></p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", {post: @post, url: post_path(current_user.username, params[:id])} %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <% @post = post %>
    <%= render @post %>
    <% like = Like.metadata(post, current_user) %>
    <% unless like.exists? %>
    <%= render partial: "likes/like_button_form", locals: {post_id: post.id} %>
     <% else %>
     <%= render partial: "likes/dislike_button_form", locals: {post_id: post.id, like_id: like.first.id} %>
     <% end %>
    <p>
      <%= link_to "Show this post", post_url(post.creator.username,@post) %>
    </p>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", {post: @post, url: posts_path} %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<% post = @post%>
<%= render @post %>

<% like = Like.metadata(post, current_user) %>
<% unless like.exists? %>
<%= render partial: "likes/like_button_form", locals: {post_id: post.id} %>
<% else %>
<%= render partial: "likes/dislike_button_form", locals: {post_id: post.id, like_id: like.first.id} %>
<% end %>

<%= render partial: "edit_links", locals: { post: @post } if current_user.username == params[:username]  %>

<div id='comments'>
<%= render partial: "comments/index", locals: { comments: @comments, level: 1 } %>
</div>

<%= stylesheet_link_tag 'posts_show_page' %>
  
<%= javascript_include_tag 'post_page' %>